import { beforeAll, describe, expect, test } from 'bun:test'
import '../DI.js'

import { fs } from '../fs/fsNode.js'
import { DazMgr } from '../mgr.js'
import type { RuntimeScene } from './RuntimeScene.js'

describe('SceneGraph', () => {
   let mgr: DazMgr
   let runtimeScene: RuntimeScene

   beforeAll(async () => {
      mgr = new DazMgr('/Volumes/ssd4t1/daz-lib/', fs)
      await mgr.loadModifiersDb()
   })

   test('should build a scene graph from a character file', async () => {
      runtimeScene = mgr.createScene()
      const characterFile = await mgr.loadGenesis9CharacterFile()
      await runtimeScene.addDazFile(characterFile)

      // Add a utility method to print the scene graph for debugging
      const sceneGraphString = (runtimeScene as any).getSceneGraphAsString()
      expect(sceneGraphString).toStrictEqual([
         '- RuntimeScene (RuntimeScene)',
         '  - Figure_Genesis9 (RVFigure)',
         '    - Bone_hip (RVBone)',
         '      - Bone_pelvis (RVBone)',
         '        - Bone_l_thigh (RVBone)',
         '          - Bone_l_shin (RVBone)',
         '            - Bone_l_foot (RVBone)',
         '              - Bone_l_toes (RVBone)',
         '                - Bone_l_bigtoe1 (RVBone)',
         '                  - Bone_l_bigtoe2 (RVBone)',
         '                - Bone_l_indextoe1 (RVBone)',
         '                  - Bone_l_indextoe2 (RVBone)',
         '                - Bone_l_midtoe1 (RVBone)',
         '                  - Bone_l_midtoe2 (RVBone)',
         '                - Bone_l_ringtoe1 (RVBone)',
         '                  - Bone_l_ringtoe2 (RVBone)',
         '                - Bone_l_pinkytoe1 (RVBone)',
         '                  - Bone_l_pinkytoe2 (RVBone)',
         '              - Bone_l_metatarsal (RVBone)',
         '          - Bone_l_thightwist1 (RVBone)',
         '          - Bone_l_thightwist2 (RVBone)',
         '        - Bone_r_thigh (RVBone)',
         '          - Bone_r_shin (RVBone)',
         '            - Bone_r_foot (RVBone)',
         '              - Bone_r_toes (RVBone)',
         '                - Bone_r_bigtoe1 (RVBone)',
         '                  - Bone_r_bigtoe2 (RVBone)',
         '                - Bone_r_indextoe1 (RVBone)',
         '                  - Bone_r_indextoe2 (RVBone)',
         '                - Bone_r_midtoe1 (RVBone)',
         '                  - Bone_r_midtoe2 (RVBone)',
         '                - Bone_r_ringtoe1 (RVBone)',
         '                  - Bone_r_ringtoe2 (RVBone)',
         '                - Bone_r_pinkytoe1 (RVBone)',
         '                  - Bone_r_pinkytoe2 (RVBone)',
         '              - Bone_r_metatarsal (RVBone)',
         '          - Bone_r_thightwist1 (RVBone)',
         '          - Bone_r_thightwist2 (RVBone)',
         '      - Bone_spine1 (RVBone)',
         '        - Bone_spine2 (RVBone)',
         '          - Bone_spine3 (RVBone)',
         '            - Bone_spine4 (RVBone)',
         '              - Bone_l_shoulder (RVBone)',
         '                - Bone_l_upperarm (RVBone)',
         '                  - Bone_l_forearm (RVBone)',
         '                    - Bone_l_hand (RVBone)',
         '                      - Bone_l_hand_anchor (RVBone)',
         '                      - Bone_l_thumb1 (RVBone)',
         '                        - Bone_l_thumb2 (RVBone)',
         '                          - Bone_l_thumb3 (RVBone)',
         '                      - Bone_l_indexmetacarpal (RVBone)',
         '                        - Bone_l_index1 (RVBone)',
         '                          - Bone_l_index2 (RVBone)',
         '                            - Bone_l_index3 (RVBone)',
         '                      - Bone_l_midmetacarpal (RVBone)',
         '                        - Bone_l_mid1 (RVBone)',
         '                          - Bone_l_mid2 (RVBone)',
         '                            - Bone_l_mid3 (RVBone)',
         '                      - Bone_l_ringmetacarpal (RVBone)',
         '                        - Bone_l_ring1 (RVBone)',
         '                          - Bone_l_ring2 (RVBone)',
         '                            - Bone_l_ring3 (RVBone)',
         '                      - Bone_l_pinkymetacarpal (RVBone)',
         '                        - Bone_l_pinky1 (RVBone)',
         '                          - Bone_l_pinky2 (RVBone)',
         '                            - Bone_l_pinky3 (RVBone)',
         '                    - Bone_l_forearmtwist1 (RVBone)',
         '                    - Bone_l_forearmtwist2 (RVBone)',
         '                  - Bone_l_upperarmtwist1 (RVBone)',
         '                  - Bone_l_upperarmtwist2 (RVBone)',
         '              - Bone_r_shoulder (RVBone)',
         '                - Bone_r_upperarm (RVBone)',
         '                  - Bone_r_forearm (RVBone)',
         '                    - Bone_r_hand (RVBone)',
         '                      - Bone_r_hand_anchor (RVBone)',
         '                      - Bone_r_thumb1 (RVBone)',
         '                        - Bone_r_thumb2 (RVBone)',
         '                          - Bone_r_thumb3 (RVBone)',
         '                      - Bone_r_indexmetacarpal (RVBone)',
         '                        - Bone_r_index1 (RVBone)',
         '                          - Bone_r_index2 (RVBone)',
         '                            - Bone_r_index3 (RVBone)',
         '                      - Bone_r_midmetacarpal (RVBone)',
         '                        - Bone_r_mid1 (RVBone)',
         '                          - Bone_r_mid2 (RVBone)',
         '                            - Bone_r_mid3 (RVBone)',
         '                      - Bone_r_ringmetacarpal (RVBone)',
         '                        - Bone_r_ring1 (RVBone)',
         '                          - Bone_r_ring2 (RVBone)',
         '                            - Bone_r_ring3 (RVBone)',
         '                      - Bone_r_pinkymetacarpal (RVBone)',
         '                        - Bone_r_pinky1 (RVBone)',
         '                          - Bone_r_pinky2 (RVBone)',
         '                            - Bone_r_pinky3 (RVBone)',
         '                    - Bone_r_forearmtwist1 (RVBone)',
         '                    - Bone_r_forearmtwist2 (RVBone)',
         '                  - Bone_r_upperarmtwist1 (RVBone)',
         '                  - Bone_r_upperarmtwist2 (RVBone)',
         '              - Bone_neck1 (RVBone)',
         '                - Bone_neck2 (RVBone)',
         '                  - Bone_head (RVBone)',
         '                    - Bone_upperteeth (RVBone)',
         '                    - Bone_lowerjaw (RVBone)',
         '                      - Bone_lowerteeth (RVBone)',
         '                      - Bone_lowerfacerig (RVBone)',
         '                        - Bone_l_lipcorner (RVBone)',
         '                        - Bone_l_liplower (RVBone)',
         '                        - Bone_liplowermiddle (RVBone)',
         '                        - Bone_r_liplower (RVBone)',
         '                        - Bone_r_lipcorner (RVBone)',
         '                        - Bone_l_cheeklower (RVBone)',
         '                        - Bone_r_cheeklower (RVBone)',
         '                        - Bone_chin (RVBone)',
         '                    - Bone_upperfacerig (RVBone)',
         '                      - Bone_l_browinner (RVBone)',
         '                      - Bone_l_browouter (RVBone)',
         '                      - Bone_r_browinner (RVBone)',
         '                      - Bone_r_browouter (RVBone)',
         '                      - Bone_centerbrow (RVBone)',
         '                      - Bone_l_eyelidupper (RVBone)',
         '                      - Bone_l_eyelidlower (RVBone)',
         '                      - Bone_r_eyelidupper (RVBone)',
         '                      - Bone_r_eyelidlower (RVBone)',
         '                      - Bone_l_squint (RVBone)',
         '                      - Bone_r_squint (RVBone)',
         '                      - Bone_l_cheek (RVBone)',
         '                      - Bone_r_cheek (RVBone)',
         '                      - Bone_l_nostril (RVBone)',
         '                      - Bone_r_nostril (RVBone)',
         '                      - Bone_lipuppermiddle (RVBone)',
         '                      - Bone_l_lipupper (RVBone)',
         '                      - Bone_r_lipupper (RVBone)',
         '                      - Bone_l_infraorbital (RVBone)',
         '                      - Bone_r_infraorbital (RVBone)',
         '                    - Bone_l_eye (RVBone)',
         '                    - Bone_r_eye (RVBone)',
         '                    - Bone_l_ear (RVBone)',
         '                    - Bone_r_ear (RVBone)',
         '            - Bone_l_pectoral (RVBone)',
         '            - Bone_r_pectoral (RVBone)',
      ])

      // Initial basic assertion
      expect(runtimeScene.children.length).toBeGreaterThan(0)
   })
})
